apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocktail-manager-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cocktail-manager-gateway
  template:
    metadata:
      labels:
        app: cocktail-manager-gateway
    spec:
      containers:
        - name: cocktail-manager-gateway
          image: us-central1-docker.pkg.dev/cocktailmanager/cocktail-manager-auth/cocktail-manager-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-gateway-secret
                  key: DATABASE_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-gateway-secret
                  key: JWT_KEY
            - name: BDD_USER
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-gateway-secret
                  key: BDD_USER
            - name: BDD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-gateway-secret
                  key: BDD_PASSWORD
            - name: BDD_NAME
              valueFrom:
                secretKeyRef:
                  name: cocktail-manager-gateway-secret
                  key: BDD_NAME
            - name: AUTH_HOST
              value: '10.4.10.68'
            - name: AUTH_PORT
              value: '3000'
          resources:
            limits:
              memory: '512Mi'
              cpu: '0.5'
            requests:
              memory: '256Mi'
              cpu: '0.1'
