apiVersion: v1
kind: Service
metadata:
  name: cocktail-manager-gateway-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: cocktail-manager-gateway